// Haftalık çalışma saatleri için önceden eğitilmiş örnekler
const TRAINING_EXAMPLES = [
    {
        prompt: "Sen bir Türkçe asistanısın. Mesai saatlerimiz öğle arası 12.00 - 13.00. Haftalık çalışma verilerini yorumla:\nPazartesi: 08:45–17:10\nSalı: 09:15–17:00\nÇarşamba: 08:30–17:30\nPerşembe: 09:00–17:15\nCuma: 08:00–16:45",
        response:
            "Bu haftalık çalışma düzeninizi analiz ettiğimde şu gözlemlerimi paylaşmak isterim:\n\n📊 **Genel Performans:**\n- Pazartesi: 7 saat 25 dakika (08:45-17:10, öğle arası 1 saat)\n- Salı: 6 saat 45 dakika (09:15-17:00, öğle arası 1 saat)\n- Çarşamba: 8 saat (08:30-17:30, öğle arası 1 saat)\n- Perşembe: 7 saat 15 dakika (09:00-17:15, öğle arası 1 saat)\n- Cuma: 7 saat 45 dakika (08:00-16:45, öğle arası 1 saat)\n\n📈 **Toplam Analiz:**\n- Toplam çalışma süresi: 37 saat 10 dakika\n- Ortalama günlük çalışma: 7 saat 26 dakika\n- Hafta sonu dinlenme: ✅ İyi bir denge\n\n✅ **Güçlü Yönler:**\n- Çarşamba günü 8 saatlik tam mesai\n- Cuma günü erken çıkış ile hafta sonuna hazırlık\n- Düzenli öğle arası rutini (12:00-13:00)\n- Hafta sonu dinlenme ile iş-yaşam dengesi\n\n⚠️ **Gelişim Alanları:**\n- Salı günü 6 saat 45 dakika (diğer günlere göre düşük)\n- Pazartesi geç başlangıç (08:45)\n\n💡 **Öneriler:**\n1. Salı günü daha erken başlayarak 7.5-8 saat hedefle\n2. Pazartesi motivasyonunu artırmak için 08:30'da başla\n3. Öğle arası rutinini koru (12:00-13:00)\n4. Hafta sonu dinlenme rutinini sürdür\n\nBu çalışma düzeni genel olarak sağlıklı ve dengeli görünüyor. Standart mesai saatlerine uygun bir yaklaşım benimsemişsiniz.",
    },
    {
        prompt: "Sen bir Türkçe asistanısın. Mesai saatlerimiz öğle arası 12.00 - 13.00. Haftalık çalışma verilerini yorumla:\nPazartesi: 08:00–18:30\nSalı: 08:30–19:00\nÇarşamba: 08:00–20:00\nPerşembe: 09:00–18:00\nCuma: 08:15–17:30\nCumartesi: 10:00–14:00",
        response:
            "Bu haftalık çalışma düzeninizi incelediğimde ciddi endişelerim var:\n\n🚨 **Kritik Uyarılar:**\n- Pazartesi: 9 saat 30 dakika (08:00-18:30, öğle arası 1 saat)\n- Salı: 9 saat 30 dakika (08:30-19:00, öğle arası 1 saat)\n- Çarşamba: 11 saat (08:00-20:00, öğle arası 1 saat) ⚠️ Aşırı yoğun\n- Perşembe: 8 saat (09:00-18:00, öğle arası 1 saat)\n- Cuma: 8 saat 15 dakika (08:15-17:30, öğle arası 1 saat)\n- Cumartesi: 3 saat (10:00-14:00)\n\n📊 **Toplam Analiz:**\n- Toplam çalışma: 49 saat 15 dakika (çok yüksek)\n- Ortalama günlük: 8 saat 12 dakika\n- Hafta sonu çalışma: İş-yaşam dengesi bozulmuş\n\n⚠️ **Risk Faktörleri:**\n1. **Tükenmişlik Riski:** Çarşamba 11 saat aşırı yoğun\n2. **Verimlilik Düşüşü:** Uzun saatler verimliliği azaltır\n3. **Sağlık Sorunları:** Stres ve yorgunluk\n4. **Sosyal Yaşam:** Cumartesi çalışma sosyal hayatı etkiler\n\n💡 **Acil Öneriler:**\n1. **Cumartesi çalışmayı durdur** - Hafta sonu tam dinlenme\n2. **Çarşamba yoğunluğunu** azalt (maksimum 9 saat)\n3. **Günlük hedef:** 8 saat (öğle arası dahil)\n4. **Molalar ekle** - her 2 saatte 15 dakika\n5. **Haftalık hedef:** 40 saat\n\nBu tempo sürdürülebilir değil. Acil önlem almanızı öneriyorum.",
    },
    {
        prompt: "Sen bir Türkçe asistanısın. Mesai saatlerimiz öğle arası 12.00 - 13.00. Haftalık çalışma verilerini yorumla:\nPazartesi: 08:00–17:00\nSalı: 08:00–17:00\nÇarşamba: 08:00–17:00\nPerşembe: 08:00–17:00\nCuma: 08:00–17:00",
        response:
            "Bu çalışma düzeninizi analiz ettiğimde çok olumlu bir tablo görüyorum:\n\n✅ **Mükemmel Denge:**\n- Her gün: 8 saat (08:00-17:00, öğle arası 12:00-13:00)\n- Toplam çalışma: 40 saat\n- Hafta sonu dinlenme: ✅ Mükemmel\n\n📈 **Güçlü Yönler:**\n1. **Tutarlılık:** Her gün aynı saat çalışma\n2. **Öngörülebilirlik:** Planlanabilir rutin\n3. **Sürdürülebilirlik:** Uzun vadede korunabilir\n4. **Verimlilik:** Optimal çalışma süresi\n5. **Dinlenme:** Hafta sonu tam dinlenme\n6. **Öğle Arası:** Düzenli 12:00-13:00 rutini\n\n🎯 **Bu Rutinin Faydaları:**\n- Biyolojik saat düzeni korunur\n- Stres seviyesi düşük kalır\n- Sosyal hayat için zaman kalır\n- Uzun vadeli sağlık korunur\n- İş performansı stabil kalır\n- Öğle arası dinlenme ile verimlilik artar\n\n💡 **Koruma Önerileri:**\n1. Bu rutini mümkün olduğunca koruyun\n2. Acil durumlar dışında değiştirmeyin\n3. Hafta sonu aktiviteleri planlayın\n4. Düzenli egzersiz ekleyin\n5. Öğle arası rutinini sürdürün\n\nBu çalışma düzeni örnek alınması gereken bir model. Tebrikler!",
    },
    {
        prompt: "Sen bir Türkçe asistanısın. Mesai saatlerimiz öğle arası 12.00 - 13.00. Haftalık çalışma verilerini yorumla:\nPazartesi: 10:00–15:00\nSalı: 11:00–16:00\nÇarşamba: 09:30–14:30\nPerşembe: 10:30–17:00\nCuma: 09:00–13:00",
        response:
            "Bu haftalık çalışma düzeninizi incelediğimde bazı endişelerim var:\n\n📊 **Genel Durum:**\n- Pazartesi: 4 saat (10:00-15:00, öğle arası 1 saat)\n- Salı: 4 saat (11:00-16:00, öğle arası 1 saat)\n- Çarşamba: 4 saat (09:30-14:30, öğle arası 1 saat)\n- Perşembe: 5 saat 30 dakika (10:30-17:00, öğle arası 1 saat)\n- Cuma: 3 saat (09:00-13:00, öğle arası 1 saat)\n\n📈 **Toplam Analiz:**\n- Toplam çalışma: 20 saat 30 dakika (çok düşük)\n- Ortalama günlük: 4 saat 6 dakika\n- En düşük gün: Cuma (3 saat)\n- En yüksek gün: Perşembe (5.5 saat)\n\n⚠️ **Tespit Edilen Sorunlar:**\n1. **Yetersiz Çalışma:** 20.5 saat çok düşük\n2. **Düzensizlik:** Günlük saatler çok değişken\n3. **Geç Başlangıçlar:** Çoğu gün 10:00'dan sonra\n4. **Verimlilik Kaybı:** Düşük saatler motivasyonu etkiler\n\n🔍 **Olası Nedenler:**\n- Motivasyon eksikliği\n- İş yoğunluğunun az olması\n- Kişisel sorunlar\n- Sağlık problemleri\n- İş tatminsizliği\n\n💡 **İyileştirme Önerileri:**\n1. **Günlük minimum 6 saat** hedefle\n2. **Haftalık hedef:** 30-35 saat\n3. **Erken başlangıç** yap (08:00-09:00)\n4. **Günlük hedefler** belirle\n5. **İş rutinini** düzenle\n\n🎯 **Aksiyon Planı:**\n- Haftaya 30 saat hedefi koy\n- Her gün en az 6 saat çalış\n- 08:00-17:00 rutini benimse\n- Haftalık performans takibi yap\n\nBu düşük tempo uzun vadede kariyer gelişimini etkileyebilir. Acil önlem almanızı öneriyorum.",
    },
    {
        prompt: "Sen bir Türkçe asistanısın. Mesai saatlerimiz öğle arası 12.00 - 13.00. Haftalık çalışma verilerini yorumla:\nPazartesi: 08:00–18:00\nSalı: 08:30–17:30\nÇarşamba: 08:00–19:00\nPerşembe: 09:00–17:00\nCuma: 08:00–16:30",
        response:
            "Bu haftalık çalışma düzeninizi analiz ettiğimde dengeli bir yoğunluk görüyorum:\n\n📊 **Genel Performans:**\n- Pazartesi: 9 saat (08:00-18:00, öğle arası 1 saat)\n- Salı: 8 saat (08:30-17:30, öğle arası 1 saat)\n- Çarşamba: 10 saat (08:00-19:00, öğle arası 1 saat)\n- Perşembe: 7 saat (09:00-17:00, öğle arası 1 saat)\n- Cuma: 7 saat 30 dakika (08:00-16:30, öğle arası 1 saat)\n\n📈 **Toplam Analiz:**\n- Toplam çalışma: 41 saat 30 dakika\n- Ortalama günlük: 8 saat 18 dakika\n- En yoğun gün: Çarşamba (10 saat)\n- En hafif gün: Perşembe (7 saat)\n\n✅ **Olumlu Yönler:**\n1. **Hafta sonu dinlenme:** İş-yaşam dengesi korunmuş\n2. **Tutarlı yoğunluk:** Günlük 7-10 saat arası\n3. **Cuma hafifleme:** Hafta sonuna hazırlık\n4. **Verimli çalışma:** Optimal saat aralığında\n5. **Öğle arası rutini:** Düzenli 12:00-13:00\n\n⚠️ **Dikkat Edilmesi Gerekenler:**\n- 41.5 saat biraz yüksek (40 saat ideal)\n- Çarşamba 10 saat sınırda\n- Uzun vadede tükenmişlik riski\n\n💡 **Optimizasyon Önerileri:**\n1. **Haftalık hedef:** 40 saat (günlük 8 saat)\n2. **Çarşamba yoğunluğunu** azalt\n3. **Mola sürelerini** artır\n4. **Stres yönetimi** teknikleri uygula\n5. **Hafta sonu aktiviteleri** planla\n\n🎯 **Sürdürülebilirlik İçin:**\n- Her 2 saatte 15 dakika mola\n- Günlük maksimum 9 saat\n- Haftalık maksimum 40 saat\n- Düzenli egzersiz ve dinlenme\n\nBu tempo kısa vadede verimli, ancak uzun vadede sürdürülebilir değil. Optimizasyon önerilerimi dikkate alın.",
    },
    {
        prompt: "Sen bir Türkçe asistanısın. Mesai saatlerimiz öğle arası 12.00 - 13.00. Haftalık çalışma verilerini yorumla:\nPazartesi: 08:30–17:30\nSalı: 08:30–17:30\nÇarşamba: 08:30–17:30\nPerşembe: 08:30–17:30\nCuma: 08:30–17:30",
        response:
            "Bu haftalık çalışma düzeninizi incelediğimde çok sağlıklı bir tablo görüyorum:\n\n📊 **Mükemmel Denge:**\n- Her gün: 8 saat (08:30-17:30, öğle arası 12:00-13:00)\n- Toplam çalışma: 40 saat\n- Günlük değişim: Yok (tamamen istikrarlı)\n- Hafta sonu dinlenme: ✅ Mükemmel\n\n✅ **Güçlü Yönler:**\n1. **İstikrar:** Her gün aynı saat çalışma\n2. **Optimal Süre:** 8 saat ideal çalışma süresi\n3. **Hafta Sonu Dengesi:** Tam dinlenme\n4. **Sürdürülebilirlik:** Uzun vadede korunabilir\n5. **Verimlilik:** Optimal performans seviyesi\n6. **Öğle Arası:** Düzenli 12:00-13:00 rutini\n\n🎯 **Bu Rutinin Avantajları:**\n- Biyolojik saat düzeni korunur\n- Stres seviyesi minimum\n- Sosyal hayat için yeterli zaman\n- Uzun vadeli sağlık korunur\n- İş performansı yüksek kalır\n- Tükenmişlik riski düşük\n- Öğle arası dinlenme ile verimlilik artar\n\n💡 **Koruma Stratejisi:**\n1. Bu rutini mümkün olduğunca koruyun\n2. Acil durumlar dışında değiştirmeyin\n3. Hafta sonu aktiviteleri planlayın\n4. Düzenli egzersiz ve hobi ekleyin\n5. Aylık performans değerlendirmesi yapın\n6. Öğle arası rutinini sürdürün\n\n🏆 **Sonuç:** Bu çalışma düzeni örnek alınması gereken bir model. Hem verimlilik hem de sağlık açısından mükemmel bir denge kurmuşsunuz. Bu rutini korumaya devam edin!",
    },
];

module.exports = {
    TRAINING_EXAMPLES,
};
