version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-app-backend-dev
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/ai_logs
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434/api
      - OLLAMA_CHAT_MODEL=llama3.2:3b
      - OLLAMA_EMBEDDING_MODEL=all-minilm
      - AI_TEMPERATURE=0.7
      - AI_MAX_TOKENS=512
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - qdrant
      - ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-app-qdrant-dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage_dev:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ai-app-mongodb-dev
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ai_logs
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ai-app-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_models_dev:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_storage_dev:
    driver: local
  mongodb_data_dev:
    driver: local
  ollama_models_dev:
    driver: local 